/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithNavbarRouteImport } from './routes/_with-navbar'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as WithNavbarIndexRouteImport } from './routes/_with-navbar/index'
import { Route as WithNavbarOnboardingRouteImport } from './routes/_with-navbar/onboarding'
import { Route as WithNavbarDashboardRouteImport } from './routes/_with-navbar/dashboard'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const WithNavbarRoute = WithNavbarRouteImport.update({
  id: '/_with-navbar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavbarIndexRoute = WithNavbarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithNavbarRoute,
} as any)
const WithNavbarOnboardingRoute = WithNavbarOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => WithNavbarRoute,
} as any)
const WithNavbarDashboardRoute = WithNavbarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WithNavbarRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WithNavbarIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof WithNavbarDashboardRoute
  '/onboarding': typeof WithNavbarOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof WithNavbarIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof WithNavbarDashboardRoute
  '/onboarding': typeof WithNavbarOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_with-navbar': typeof WithNavbarRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_with-navbar/dashboard': typeof WithNavbarDashboardRoute
  '/_with-navbar/onboarding': typeof WithNavbarOnboardingRoute
  '/_with-navbar/': typeof WithNavbarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/dashboard' | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/dashboard' | '/onboarding'
  id:
    | '__root__'
    | '/_auth'
    | '/_with-navbar'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_with-navbar/dashboard'
    | '/_with-navbar/onboarding'
    | '/_with-navbar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  WithNavbarRoute: typeof WithNavbarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_with-navbar': {
      id: '/_with-navbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithNavbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-navbar/': {
      id: '/_with-navbar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithNavbarIndexRouteImport
      parentRoute: typeof WithNavbarRoute
    }
    '/_with-navbar/onboarding': {
      id: '/_with-navbar/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof WithNavbarOnboardingRouteImport
      parentRoute: typeof WithNavbarRoute
    }
    '/_with-navbar/dashboard': {
      id: '/_with-navbar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WithNavbarDashboardRouteImport
      parentRoute: typeof WithNavbarRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface WithNavbarRouteChildren {
  WithNavbarDashboardRoute: typeof WithNavbarDashboardRoute
  WithNavbarOnboardingRoute: typeof WithNavbarOnboardingRoute
  WithNavbarIndexRoute: typeof WithNavbarIndexRoute
}

const WithNavbarRouteChildren: WithNavbarRouteChildren = {
  WithNavbarDashboardRoute: WithNavbarDashboardRoute,
  WithNavbarOnboardingRoute: WithNavbarOnboardingRoute,
  WithNavbarIndexRoute: WithNavbarIndexRoute,
}

const WithNavbarRouteWithChildren = WithNavbarRoute._addFileChildren(
  WithNavbarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  WithNavbarRoute: WithNavbarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
